version: '3.1'
name: EventBrokering-dev
services:
  mongo:
    image: dolittle/mongodb
    hostname: mongo
    ports:
      - 27017:27017
    logging:
      driver: none

  runtime-orders:
    image: dolittle/runtime:8.0.1-mithrandir.5
    volumes:
      - ./resources-orders.json:/app/.dolittle/resources.json
      - ./tenants.json:/app/.dolittle/tenants.json
      - ./microservices.json:/app/.dolittle/microservices.json
      - ./event-horizon-consents.json:/app/.dolittle/event-horizon-consents.json
      - ./appsettings.json:/app/appsettings.json
    environment:
      - "DOLITTLE__RUNTIME__EVENTSTORE__BACKWARDSCOMPATIBILITY__VERSION=V7"
    ports:
      - 50069:50053
      - 51068:51052